---
name: Woodley
author: Andre Woodley Jr.
url: https://github.com/andrewoodleyjr/andre-woodley-jr-theme
posts_per_page:
  include_in_settings: false
  default: 10
settings:
- id: title
  label: Site Title
  default: Site Title
  type: text
- id: tagline
  label: Site Tagline
  default: Site Tagline
  type: text
- id: headline
  label: Headline
  default: Theme Elements
  type: text
- id: subheadline
  label: SubHeadline
  default: Sub Headline
  type: text
- id: contact
  label: Contact
  default: hello@email.com
  type: text
- id: recognition_text
  label: Recongnition Statement
  default: Provide recongnition statement here
  type: text 
- id: recognition_items
  label: Recongnition Items (max 450 characters)
  default: Title1*Description1|Title2*Description2|Title3*Description3
  type: text 
- id: dark_color
  label: Dark Color
  default: "#000"
  type: color
- id: light_color
  label: Light Color
  default: "#fefefe"
  type: color