---
name: Woodley
author: Andre Woodley Jr.
url: https://github.com/andrewoodleyjr/andre-woodley-jr-theme
posts_per_page:
  include_in_settings: false
  default: 10
settings:
- id: title
  label: Site Title
  default: Site Title
  type: text
- id: tagline
  label: Site Tagline
  default: Site Tagline
  type: text
- id: headline
  label: Headline
  default: Theme Elements
  type: text
- id: subheadline
  label: SubHeadline
  default: Sub Headline
  type: text
- id: contact
  label: Contact
  default: hello@email.com
  type: text
- id: copyright_start_date
  label: Copyright Start Date
  default: 1990
  type: text
- id: copyright_end_date_now
  label: Copyright End Date Now
  default: true
  type: checkbox
- id: recognition_text
  label: Recongnition Statement
  default: Provide recongnition statement here
  type: text
- id: recognition_items
  label: Recongnition Items (max 450 characters)
  default: Title1*Description1|Title2*Description2|Title3*Description3
  type: text
- id: dark_color
  label: Dark Color
  default: "#000"
  type: color
- id: light_color
  label: Light Color
  default: "#fefefe"
  type: color
- id: search_result_color
  label: Search Result Color
  default: "#000"
  type: color
- id: recent_post_in_header
  label: Show Recent Post in Main Header
  default: false
  type: checkbox
